// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TheQTablet.iOS
{
	public partial class DetailSimulationView : UIViewController
	{
		public DetailSimulationView (IntPtr handle) : base (handle)
		{
		}
	}
}
