// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using UIKit;

namespace TheQTablet.iOS
{
	[MvxFromStoryboard("Main")]
	public partial class LightPolaritationStoryView : UIViewController
	{
		public LightPolaritationStoryView (IntPtr handle) : base (handle)
		{
		}
	}
}
