// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using Cirrious.FluentLayouts.Touch;
using Foundation;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using TheQTablet.Core.ViewModels.Main;
using UIKit;
using MvvmCross.Platforms.Ios.Views;
using SceneKit;

namespace TheQTablet.iOS
{
	[MvxFromStoryboard("Main")]
	public partial class StartLessonScreenView : MvxViewController<StartLessonViewModel>
	{
		public StartLessonScreenView (IntPtr handle) : base (handle)
		{
		}

        SCNScene scene;

        SCNView sceneView;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //scene = SCNScene.FromFile("Art.scnassets/environement01.scn");

            //sceneView = new SCNView(View.Frame);
            //sceneView.BackgroundColor = UIColor.Clear;
            //sceneView.AutoresizingMask = UIViewAutoresizing.All;
            //sceneView.Scene = scene;
            //sceneView.AllowsCameraControl = true;

            //this.View.InsertSubview(sceneView,0);

            startButton.BackgroundColor = ColorPalette.Accent;
            startButton.Font = FontGenerator.GenerateFont(17, UIFontWeight.Bold);
            startButton.SetTitleColor(ColorPalette.AccentLight, UIControlState.Normal);
            startButton.SetTitle("LET'S BEGIN", UIControlState.Normal);
            startButton.SetTitle("LET'S BEGIN", UIControlState.Highlighted);
            startButton.SetTitle("LET'S BEGIN", UIControlState.Selected);
 
            startButton.Layer.CornerRadius = 6;

            backButton.BackgroundColor = ColorPalette.AccentLight;
            backButton.SetTitleColor(ColorPalette.SecondaryText,UIControlState.Normal);
            backButton.SetTitleColor(ColorPalette.SecondaryText, UIControlState.Highlighted);
            backButton.SetTitleColor(ColorPalette.SecondaryText, UIControlState.Selected);
            backButton.Font = FontGenerator.GenerateFont(17, UIFontWeight.Bold);
            backButton.SetTitle("BACK", UIControlState.Normal);
            backButton.SetTitle("BACK", UIControlState.Highlighted);
            backButton.SetTitle("BACK", UIControlState.Selected);

            backButton.Layer.CornerRadius = 6;

            var set = this.CreateBindingSet<StartLessonScreenView,StartLessonViewModel>();
            set.Bind(startButton).For("TouchUpInside").To(vm => vm.StartLessonCommand);
            set.Apply();
        }
    }
}
