// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using TheQTablet.Core.ViewModels.Main;
using UIKit;

namespace TheQTablet.iOS
{
	[MvxFromStoryboard("Main")]
	public partial class StoryContainerView : MvxViewController<StoryContainerViewModel>
	{
		public StoryContainerView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var set = this.CreateBindingSet();
            set.Bind(nextButton).For("TouchUpInside").To(vm => vm.NextCommand);
            set.Bind(storyLabel).To(vm => vm.StoryLabel);
            set.Apply();
        }
    }
}
